"use client";
import { Activity, Plus, Router, Trash2, X } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
type RouterItem = { id: string; name: string; endpoint: string; createdAt: string }; type Snapshot = { routerId: string; connected: boolean; clients?: unknown[] };
export default function RoutersPage() {
 const [routers, setRouters] = useState<RouterItem[]>([]), [snapshots, setSnapshots] = useState<Snapshot[]>([]), [open, setOpen] = useState(false), [saving, setSaving] = useState(false), [error, setError] = useState("");
 const refresh = () => fetch("/api/overview").then(r => r.json()).then((data: { routers: RouterItem[]; snapshots: Snapshot[] }) => { setRouters(data.routers); setSnapshots(data.snapshots); }).catch(() => setError("Could not load devices."));
 useEffect(() => { void refresh(); }, []);
 async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); try { const form = new FormData(event.currentTarget); const response = await fetch("/api/routers", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); const result = await response.json().catch(() => ({})); if (!response.ok) { setError(result.error ?? "Could not add device."); return; } setOpen(false); void refresh(); } catch { setError("Could not reach the controller. Please try again."); } finally { setSaving(false); } }
 async function remove(id: string) { await fetch(`/api/routers/${id}`, { method: "DELETE" }); refresh(); }
 return <div className="mx-auto max-w-7xl p-5 md:p-9"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Infrastructure</p><h1 className="page-title">OpenWrt Devices</h1><p className="subtitle">Manage every adopted gateway and access point from one controller.</p></div><button className="button-primary" onClick={() => setOpen(true)}><Plus size={17}/> Add OpenWrt Device</button></div>
 <section className="panel mt-8 overflow-hidden"><div className="grid grid-cols-[1.5fr_repeat(4,1fr)] gap-4 border-b border-slate-800 px-5 py-3 text-[11px] font-semibold uppercase tracking-widest text-slate-500"><span>Device</span><span>Status</span><span>Endpoint</span><span>Clients</span><span>Actions</span></div>{routers.length ? routers.map(router => { const snapshot = snapshots.find(item => item.routerId === router.id); return <div key={router.id} className="grid grid-cols-[1.5fr_repeat(4,1fr)] items-center gap-4 border-b border-slate-800/80 px-5 py-5 last:border-0"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-lg bg-sky-400/10 text-sky-400"><Router size={19}/></span><div><p className="font-medium">{router.name}</p><p className="mt-1 text-xs text-slate-500">Added {new Date(router.createdAt).toLocaleDateString()}</p></div></div><span className={`status-pill ${snapshot?.connected ? "!bg-emerald-400/10 !text-emerald-300" : ""}`}><i className={snapshot?.connected ? "!bg-emerald-400" : ""}/>{snapshot ? (snapshot.connected ? "Connected" : "Unavailable") : "Awaiting poll"}</span><span className="truncate text-sm text-slate-400">{router.endpoint}</span><span className="text-slate-400">{snapshot?.clients?.length ?? "—"}</span><button aria-label={`Remove ${router.name}`} className="w-fit text-slate-500 hover:text-rose-400" onClick={() => remove(router.id)}><Trash2 size={17}/></button></div>}) : <div className="grid place-items-center gap-3 px-6 py-20 text-center"><span className="grid h-12 w-12 place-items-center rounded-full bg-slate-900 text-sky-400"><Activity size={22}/></span><div><p className="font-medium">No OpenWrt devices yet</p><p className="mt-1 text-sm text-slate-500">Adopt a router to begin collecting client and traffic data.</p></div><button className="button-secondary mt-2" onClick={() => setOpen(true)}>Add your first device</button></div>}</section>
 {open && <div className="modal-backdrop"><form onSubmit={submit} className="modal-card"><div className="flex items-start justify-between"><div><p className="eyebrow">Adopt device</p><h2 className="mt-1 text-xl font-semibold">Add OpenWrt Device</h2><p className="mt-2 text-sm text-slate-500">Credentials are stored on this controller and never sent to browsers.</p></div><button type="button" onClick={() => setOpen(false)} className="text-slate-500 hover:text-white"><X/></button></div><div className="mt-6 grid gap-4"><label>Device name<input name="name" required placeholder="Office Gateway"/></label><label>uBus endpoint<input name="endpoint" type="url" required placeholder="https://192.168.1.1/ubus"/></label><div className="grid grid-cols-2 gap-4"><label>Username<input name="username" required defaultValue="root"/></label><label>Password<input name="password" type="password" required/></label></div></div>{error && <p className="mt-4 text-sm text-rose-400">{error}</p>}<div className="mt-7 flex justify-end gap-3"><button type="button" className="button-secondary" onClick={() => setOpen(false)}>Cancel</button><button disabled={saving} className="button-primary">{saving ? "Adding…" : "Add device"}</button></div></form></div>}</div>;
}
