"use client";

import { Check, ChevronRight, CircleAlert, Copy, Filter, Network, Plus, Radio, RefreshCw, Route, Search, Server, ShieldCheck, SlidersHorizontal, SwitchCamera, Wifi, Wrench } from "lucide-react";
import { useMemo, useState } from "react";

type Section = "Interfaces" | "Wireless" | "Switch" | "Routing" | "DHCP" | "DNS" | "Diagnostics" | "Firewall";
const sections: { name: Section; icon: typeof Network; description: string }[] = [
  { name: "Interfaces", icon: Network, description: "WAN, LAN and VLAN connections" }, { name: "Wireless", icon: Wifi, description: "WiFi networks and radios" }, { name: "Switch", icon: SwitchCamera, description: "Ports, VLANs and profiles" }, { name: "Routing", icon: Route, description: "Static routes and policy rules" }, { name: "DHCP", icon: Server, description: "Leases, pools and reservations" }, { name: "DNS", icon: Search, description: "Resolvers and local records" }, { name: "Diagnostics", icon: Wrench, description: "Tools and service status" }, { name: "Firewall", icon: ShieldCheck, description: "Zones, rules and port forwards" },
];
const details: Record<Section, { eyebrow: string; title: string; description: string }> = {
  Interfaces: { eyebrow: "Network", title: "Interfaces", description: "Configure the uplinks and local networks exposed by your OpenWrt gateway." }, Wireless: { eyebrow: "Network", title: "WiFi", description: "Create wireless networks and tune each radio from one place." }, Switch: { eyebrow: "Network", title: "Switching", description: "Manage physical ports, VLAN assignments and traffic profiles." }, Routing: { eyebrow: "Network", title: "Routing", description: "Define static paths and inspect the active route table." }, DHCP: { eyebrow: "Services", title: "DHCP Server", description: "Control address pools and reserve fixed addresses for your devices." }, DNS: { eyebrow: "Services", title: "DNS", description: "Choose upstream resolvers and manage local hostname records." }, Diagnostics: { eyebrow: "System", title: "Diagnostics", description: "Run safe network checks directly against your OpenWrt gateway." }, Firewall: { eyebrow: "Security", title: "Firewall & Security", description: "Protect networks with zones, traffic rules and port forwards." },
};
function Toggle({ enabled, onChange }: { enabled: boolean; onChange: () => void }) { return <button type="button" onClick={onChange} className={`toggle ${enabled ? "toggle-on" : ""}`} aria-label="Toggle setting"><span/></button> }
function ActionButton({ children, primary = false, onClick }: { children: React.ReactNode; primary?: boolean; onClick?: () => void }) { return <button onClick={onClick} className={primary ? "button button-primary" : "button"}>{children}</button> }
function Status({ children = "Online" }: { children?: React.ReactNode }) { return <span className="status"><i/> {children}</span> }
function Interfaces() { return <div className="settings-stack"><div className="table-card"><div className="table-toolbar"><div><b>Configured interfaces</b><span>3 interfaces · Last updated just now</span></div><ActionButton primary><Plus size={16}/> Add interface</ActionButton></div><div className="data-table"><div className="data-head interface-grid"><span>Name</span><span>Protocol</span><span>Device</span><span>IPv4 address</span><span>Status</span><span/></div>{[["WAN", "DHCP client", "eth0", "100.72.16.84", "Online"], ["LAN", "Static address", "br-lan", "192.168.1.1/24", "Online"], ["IoT", "Static address", "br-iot.20", "192.168.20.1/24", "Online"]].map(row => <div className="data-row interface-grid" key={row[0]}><b>{row[0]}</b><span>{row[1]}</span><code>{row[2]}</code><span>{row[3]}</span><Status>{row[4]}</Status><button className="row-action">•••</button></div>)}</div></div><InfoNotice text="Changes are staged safely and are only applied to OpenWrt after you save."/></div> }
function Wireless() { const [enabled, setEnabled] = useState(true); return <div className="settings-stack"><div className="radio-cards">{[["OpenFi Home", "2.4 GHz · 20 MHz · Channel 1", "WPA2/WPA3 Personal", "24 clients"], ["OpenFi Home", "5 GHz · 80 MHz · Channel 36", "WPA2/WPA3 Personal", "18 clients"]].map((radio, i) => <section className="radio-card" key={radio[1]}><div className="radio-icon"><Wifi size={22}/></div><div className="radio-content"><div className="radio-title"><b>{radio[0]}</b><Status>Broadcasting</Status></div><p>{radio[1]}</p><div className="radio-meta"><span>{radio[2]}</span><span>{radio[3]}</span></div></div><ActionButton>Configure</ActionButton></section>)}</div><section className="form-card"><div className="form-title"><div><b>Global radio settings</b><p>Apply radio availability rules across all wireless networks.</p></div><Toggle enabled={enabled} onChange={() => setEnabled(!enabled)}/></div><div className="form-row"><label>Country <select defaultValue="NL"><option value="NL">Netherlands</option><option>Belgium</option></select></label><label>Band steering <select defaultValue="Prefer 5 GHz"><option>Prefer 5 GHz</option><option>Balanced</option></select></label></div></section></div> }
function Switch() { return <div className="settings-stack"><section className="table-card"><div className="table-toolbar"><div><b>Gateway ports</b><span>OpenFi Gateway · 4 ports available</span></div><ActionButton><SlidersHorizontal size={16}/> Port manager</ActionButton></div><div className="port-grid">{["WAN", "LAN 1", "LAN 2", "LAN 3"].map((port, i) => <div className="port" key={port}><span className={`port-light ${i === 3 ? "dim" : ""}`}/><b>{port}</b><small>{i === 0 ? "Internet · 1 GbE" : i === 3 ? "Disabled" : "OpenFi LAN · 1 GbE"}</small><em>{i === 3 ? "Disconnected" : "Connected"}</em></div>)}</div></section><section className="table-card"><div className="table-toolbar"><div><b>Virtual networks</b><span>VLAN assignments used by switch ports</span></div><ActionButton primary><Plus size={16}/> Create VLAN</ActionButton></div><div className="data-table"><div className="data-head vlan-grid"><span>Name</span><span>VLAN ID</span><span>Network</span><span>Ports</span><span/></div>{[["Default", "1", "LAN", "LAN 1, LAN 2"], ["IoT", "20", "IoT", "LAN 2"]].map(row => <div className="data-row vlan-grid" key={row[0]}><b>{row[0]}</b><code>{row[1]}</code><span>{row[2]}</span><span>{row[3]}</span><button className="row-action">•••</button></div>)}</div></section></div> }
function Routing() { return <TableSection title="Static routes" subtitle="Routes are evaluated in priority order." add="Add route" cols={["Destination", "Gateway", "Interface", "Metric"]} rows={[["0.0.0.0/0", "100.72.16.1", "WAN", "10"], ["10.10.0.0/16", "192.168.1.254", "LAN", "20"]]}/> }
function DHCP() { return <div className="settings-stack"><section className="form-card"><div className="form-title"><div><b>LAN DHCP server</b><p>Distribute addresses to clients connected to the LAN network.</p></div><Toggle enabled={true} onChange={() => {}}/></div><div className="form-row three"><label>Start address<input defaultValue="192.168.1.100"/></label><label>End address<input defaultValue="192.168.1.250"/></label><label>Lease time<select defaultValue="12 hours"><option>12 hours</option><option>24 hours</option></select></label></div></section><TableSection title="Static leases" subtitle="Reserved addresses are always assigned to the matching device." add="Add reservation" cols={["Name", "MAC address", "IP address", "Network"]} rows={[["Office printer", "48:22:54:9A:CC:10", "192.168.1.10", "LAN"], ["NAS", "E0:63:DA:78:1E:04", "192.168.1.20", "LAN"]]}/></div> }
function DNS() { return <div className="settings-stack"><section className="form-card"><div className="form-title"><div><b>Upstream DNS</b><p>Queries that cannot be resolved locally are forwarded to these resolvers.</p></div><Status>Encrypted DNS off</Status></div><div className="form-row"><label>Primary DNS<input defaultValue="1.1.1.1"/></label><label>Secondary DNS<input defaultValue="1.0.0.1"/></label></div></section><TableSection title="Local DNS records" subtitle="Custom hostnames available to devices on your network." add="Add record" cols={["Hostname", "Address", "Type", "Network"]} rows={[["nas.openfi", "192.168.1.20", "A", "LAN"], ["printer.openfi", "192.168.1.10", "A", "LAN"]]}/></div> }
function Diagnostics() { const [result, setResult] = useState("Ready to run a diagnostic."); return <div className="settings-stack"><section className="diagnostic-card"><div><span className="tool-icon"><Wrench size={20}/></span><b>Network tools</b><p>Ping, traceroute and DNS lookup run from your OpenWrt gateway.</p></div><div className="diagnostic-form"><label>Target host<input defaultValue="1.1.1.1"/></label><ActionButton primary onClick={() => setResult("Ping complete: 1.1.1.1 responded in 11 ms (0% packet loss).")}>Run ping</ActionButton></div><output><Check size={17}/>{result}</output></section><section className="table-card"><div className="table-toolbar"><div><b>Service health</b><span>Live status from your gateway</span></div><ActionButton><RefreshCw size={15}/> Refresh</ActionButton></div><div className="health-grid">{[["Internet", "Reachable", "11 ms"], ["DNS resolver", "Healthy", "1.1.1.1"], ["DHCP service", "Running", "3 active leases"], ["Firewall", "Protected", "72 rules loaded"]].map(item => <div key={item[0]}><Status>{item[1]}</Status><b>{item[0]}</b><small>{item[2]}</small></div>)}</div></section></div> }
function Firewall() { return <div className="settings-stack"><div className="zone-cards">{[["WAN", "Reject", "WAN → LAN blocked"], ["LAN", "Accept", "LAN → WAN allowed"], ["IoT", "Accept", "IoT → WAN only"]].map(zone => <section key={zone[0]}><span className="shield"><ShieldCheck size={19}/></span><div><b>{zone[0]}</b><p>{zone[2]}</p></div><span className={`policy ${zone[1] === "Reject" ? "reject" : ""}`}>{zone[1]}</span><ChevronRight size={18}/></section>)}</div><TableSection title="Port forwards" subtitle="Make a service on your local network available from the internet." add="Add port forward" cols={["Name", "Protocol", "External port", "Forward to"]} rows={[["—", "No port forwards configured", "", ""]]}/></div> }
function InfoNotice({ text }: { text: string }) { return <div className="info-notice"><CircleAlert size={17}/>{text}</div> }
function TableSection({ title, subtitle, add, cols, rows }: { title: string; subtitle: string; add: string; cols: string[]; rows: string[][] }) { return <section className="table-card"><div className="table-toolbar"><div><b>{title}</b><span>{subtitle}</span></div><ActionButton primary><Plus size={16}/>{add}</ActionButton></div><div className="simple-table" style={{ gridTemplateColumns: `repeat(${cols.length}, minmax(110px, 1fr)) 35px` }}>{cols.map(c => <span className="data-head" key={c}>{c}</span>)}<span className="data-head"/>{rows.map((row, ri) => <div className="table-line" style={{ gridColumn: `1 / span ${cols.length + 1}`, gridTemplateColumns: `repeat(${cols.length}, minmax(110px, 1fr)) 35px` }} key={ri}>{row.map((cell, ci) => <span key={ci}>{cell}</span>)}<button className="row-action">•••</button></div>)}</div></section> }
export default function SettingsPage() { const [selected, setSelected] = useState<Section>("Interfaces"); const [query, setQuery] = useState(""); const list = useMemo(() => sections.filter(s => s.name.toLowerCase().includes(query.toLowerCase())), [query]); const Current = ({ Interfaces, Wireless, Switch, Routing, DHCP, DNS, Diagnostics, Firewall } as Record<Section, () => React.ReactNode>)[selected]; const current = details[selected]; return <div className="settings-shell"><aside className="settings-nav"><div className="settings-search"><Search size={16}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search settings"/></div><p className="settings-label">CONFIGURATION</p>{list.map(item => { const Icon = item.icon; return <button className={`settings-link ${selected === item.name ? "selected" : ""}`} onClick={() => setSelected(item.name)} key={item.name}><Icon size={18}/><span>{item.name}</span><ChevronRight size={15}/></button> })}<div className="apply-card"><span><Check size={15}/></span><div><b>All changes saved</b><p>Your gateway is in sync</p></div></div></aside><main className="settings-content"><div className="content-header"><div><p className="eyebrow">{current.eyebrow}</p><h1>{current.title}</h1><p>{current.description}</p></div><div className="header-actions"><ActionButton><Filter size={16}/> Filter</ActionButton><ActionButton><Copy size={16}/> Export</ActionButton></div></div><Current/></main></div> }
